export enum EventType {
    USER_CREATED,
    USER_UPDATED,
    USER_DELETED,
    INSTITUTION_CREATED,
    INSTITUTION_UPDATED,
    INSTITUTION_DELETED,
    USER_INVITED,
    USER_JOINED_INSTITUTION,
    USER_LEFT_INSTITUTION,
    USER_REMOVED_FROM_INSTITUTION
}

export interface Event {
    type: EventType;
    data: any;
}