version: '3.8'
services:
  nginx-proxy:
    image: nginx:1.25.3-alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
      - auth-service
      - payments-service
      - institutions-service
    networks:
      - app

  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
      - ./shared:/usr/src/shared
    ports:
      - '3001:3001'
    environment:
      APP_NAME: 'auth-service'
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/auth?schema=public'
      REDIS_URL: 'redis://redis:6379'
      SECRET: 'jfdsakjfbdsakjfndsalkjlkdsahlkdsj'
      PORT: 3001
    networks:
      - app
    depends_on:
      - postgres
      - redis

  payments-service:
    build:
      context: payments
      dockerfile: Dockerfile.dev
    volumes:
      - ./payments:/usr/src/app
      - /usr/src/app/node_modules
      - ./shared:/usr/src/shared
    ports:
      - '3002:3002'
    environment:
      APP_NAME: 'payments-service'
      AUTH_URL: 'http://auth-service:3001'
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/payments?schema=public'
      REDIS_URL: 'redis://redis:6379'
      STRIPE_KEY: ${STRIPE_KEY}
      PORT: 3002
    networks:
      - app
    depends_on:
      - postgres
      - redis
      - auth-service

  institutions-service:
    build:
      context: ./institutions
      dockerfile: Dockerfile.dev
    volumes:
      - ./institutions:/usr/src/app
      - /usr/src/app/node_modules
      - ./shared:/usr/src/shared
    ports:
      - '3003:3003'
    environment:
      APP_NAME: 'institutions-service'
      AUTH_URL: 'http://auth-service:3001'
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/institutions?schema=public'
      REDIS_URL: 'redis://redis:6379'
      PORT: 3003
    networks:
      - app
    depends_on:
      - postgres
      - redis
      - auth-service

  rabbitmq:
    image: rabbitmq:3.8.9-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    networks:
      - app

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app

volumes:
  postgres:
  rabbitmq:

networks:
  app:
    driver: bridge