version: '3.8'
services:
  auth-service:
    build:
      context: ./auth
      dockerfile: Dockerfile.dev
    volumes:
      - ./auth:/usr/src/app
      - /usr/src/app/node_modules
      - ./shared:/usr/src/shared
    ports:
      - '3001:3001'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/auth?schema=public'
      REDIS_URL: 'redis://redis:6379'
      NATS_URL: 'nats://nats:4222'
      SECRET: 'jfdsakjfbdsakjfndsalkjlkdsahlkdsj'
      PORT: 3001
    networks:
      - app
    depends_on:
      - postgres
      - redis
      - nats

  orders-service:
    build:
      context: ./orders
      dockerfile: Dockerfile.dev
    volumes:
      - ./orders:/usr/src/app
      - /usr/src/app/node_modules
      - ./shared:/usr/src/shared
    ports:
      - '3002:3002'
    environment:
      AUTH_URL: 'http://auth-service:3001'
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/orders?schema=public'
      REDIS_URL: 'redis://redis:6379'
      NATS_URL: 'nats://nats:4222'
      STRIPE_KEY: ${STRIPE_KEY}
      PORT: 3002
    networks:
      - app
    depends_on:
      - postgres
      - redis
      - nats
      - auth-service

  subscriptions-service:
    build:
      context: ./subscriptions
      dockerfile: Dockerfile.dev
    volumes:
      - ./subscriptions:/usr/src/app
      - /usr/src/app/node_modules
      - ./shared:/usr/src/shared
    ports:
      - '3003:3003'
    environment:
      AUTH_URL: 'http://auth-service:3001'
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/subscriptions?schema=public'
      REDIS_URL: 'redis://redis:6379'
      NATS_URL: 'nats://nats:4222'
      STRIPE_KEY: ${STRIPE_KEY}
      PORT: 3003
    networks:
      - app
    depends_on:
      - postgres
      - redis
      - nats
      - auth-service

  nats:
    image: nats
    restart: always
    ports:
      - '4222:4222'
    networks:
      - app

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - app

volumes:
  postgres:

networks:
  app:
    driver: bridge